// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Lesson
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int CourseId { get; set; }

    public virtual Course Course { get; set; }

    public virtual Quizz Quizz { get; set; }
}