// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class MenteeScore
{
    public int UserId { get; set; }

    public int QuizId { get; set; }

    public double? Score { get; set; }

    public virtual Quizz Quiz { get; set; }

    public virtual User User { get; set; }
}