// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class QuestionType
{
    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}