// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Quizz
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int LessionId { get; set; }

    public string Name { get; set; }

    public virtual Lesson IdNavigation { get; set; }

    public virtual ICollection<MenteeScore> MenteeScores { get; set; } = new List<MenteeScore>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}