// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class ResetPasswordToken
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string ResetToken { get; set; }

    public DateTime ExpiredAt { get; set; }

    public bool IsUsed { get; set; }

    public DateTime CreateAt { get; set; }

    public virtual User User { get; set; }
}