// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class SubLesson
{
    public int SubLessonId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Description { get; set; }

    public int LessionId { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? IsLocked { get; set; }

    public long? VideoDuration { get; set; }

    public string VideoLink { get; set; }
}