// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class User
{
    public int Id { get; set; }

    public string Usename { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Email { get; set; }

    public bool IsLocked { get; set; }

    public int RoleId { get; set; }

    public string Password { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual ICollection<MenteeScore> MenteeScores { get; set; } = new List<MenteeScore>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}